const HEADER_HEIGHT = 64;
const HEADER_HEIGHT_TABLE = 51;
const PAGINATION_HEIGHT_TABLE = 56;

export const HEADER_SCROLL_SPACE =
  HEADER_HEIGHT + HEADER_HEIGHT_TABLE + PAGINATION_HEIGHT_TABLE - 30;
